name: myenv
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.9
  - numpy
  - scipy
  - scikit-learn
  - memory_profiler
  - cvxpy
  - matplotlib
  - pip
  - pip:
      - cvxpylayers

